### ISSUE TITLE
make release 报错

### ISSUE THREAD

**Issue by chengcxy** [Breeze0806/go-etl#28]
make release 报错
tools/wizard.go:147:29: undefined: generateScript
tools/wizard.go:150:31: undefined: ext
# runtime/cgo
ld: warning: directory not found for option '-L/Users/play/go/src/github.com/ibmdb/clidriver/lib'
../../../../../../pkg/mod/github.com/ibmdb/go_ibm_db@v0.4.4/api/api_unix.go:14:11: fatal error: 'sqlcli1.h' file not found
 include <sqlcli1.h>
          ^~~~~~~~~~~
1 error generated.

ld: warning: directory not found for option '-L/Users/play/go/src/github.com/ibmdb/clidriver/lib'

ld: warning: directory not found for option '-L/Users/play/go/src/github.com/ibmdb/clidriver/lib'
ld: warning: directory not found for option '-L/Users/play/go/src/github.com/ibmdb/clidriver/lib'
make: *** [release] Error 2

**Comment by Breeze0806** [comment]
请先运行make dependencies，或者在编译时选择忽略数据源db2。

**Comment by chengcxy** [comment]
加了环境变量去掉了db2依赖

make dependencies ok


➜  go-etl git:(main) ✗ make release
# github.com/Breeze0806/go-etl/cmd/datax/tools
tools/wizard.go:147:29: undefined: generateScript
tools/wizard.go:150:31: undefined: ext
make: *** [release] Error 2

**Comment by Breeze0806** [comment]
因为oracle也依赖odbc库的，编译时也得依赖cgo，你在忽略包变量里再要加oracle，否则编译通不过的。

**Comment by chengcxy** [comment]
> MAC的话，我接触不多，从报错看这是因为oracle数据源也需要依赖odbc库的，编译时也得依赖cgo，你在忽略包变量里再要加oracle，即export IGNORE_PACKAGES=db2，oracle 这样应该能够编译通过。

linux 编译也不行 😶

**Comment by Breeze0806** [comment]
这个不要加CGO_ENABLED=0

**Comment by chengcxy** [comment]
好的 我再试试
