### ISSUE TITLE
I got a error: filed:t_unsigned_bigint type(UNSIGNED BIGINT) is not supportted

### ISSUE THREAD

**Issue by hellousworld** [Breeze0806/go-etl#31]
Hello friend,
My software version:  
win10
go-etl v0.1.7
reader:   MySQL5.7.26 (use init.sql init the database) 
writer:   MySQL5.7.26  (use init.sql init the database) 

After run datax -c config.json 
I got a error:   filed:t_unsigned_bigint type(UNSIGNED BIGINT) is not supportted,  
How to fix it, thanks.

config.json 
{
    "core" : {
        "container": {
            "job":{
                "id": 1,
                "sleepInterval":100
            }
        }
    },
    "job":{
        "content":[
            {
                "reader":{
                    "name": "mysqlreader",
                    "parameter": {
                        "username": "root",
                        "password": "123456",
                        "column": ["*"],
                        "connection":  {
                                "url": "tcp(127.0.0.1:3306)/source?parseTime=false",
                                "table": {
                                    "db":"source",
                                    "name":"type_table"
                                }
                            },
                        "where": ""
                    }
                },
                "writer":{
                    "name": "mysqlwriter",
                    "parameter": {
                        "username": "root",
                        "password": "123456",
                        "writeMode": "insert",
                        "column": ["*"],
                        "session": [],
                        "preSql": [],
                        "connection":  {
                                "url": "tcp(127.0.0.1:3306)/mysql?parseTime=false",
                                "table": {
                                    "db":"destination",
                                    "name":"type_table"
                                }
                         },
                        "batchTimeout": "1s",
                        "batchSize":1000
                    }
                },
               "transformer":[]
            }
        ]
    }
}

**Comment by Breeze0806** [comment]
Thanks for your feedback，I will try to reproduce it.

**Comment by Breeze0806** [comment]
You can download the [v0.1.8](https://github.com/Breeze0806/go-etl/releases/tag/v0.1.8) version to solve this problem

**Comment by hellousworld** [comment]
thanks a lot. I try it.
