### ISSUE TITLE
如何在macos下进行编译

### ISSUE THREAD

**Issue by zsy619** [Breeze0806/go-etl#44]
如何在macos系统下进行交叉编译

**Comment by zsy619** [comment]
@Shane-XB-Qian 帮忙看下

**Comment by Breeze0806** [comment]
请您描述一下具体遇到了什么问题？

**Comment by zsy619** [comment]
在macos环境下开发的

**Comment by Breeze0806** [comment]
我指的是你遇到了什么问题，如报错啥的，否则这边也不知要怎么回复你？

**Comment by Breeze0806** [comment]
[go-etl在macos下编译若干问题](https://zsy619.github.io/golang/macos_go_etl_build） @zsy619 谢谢你的提交，期待你的pr
