### ISSUE TITLE
多数据源抽取数据并聚合

### ISSUE THREAD

**Issue by lhg814385644** [Breeze0806/go-etl#51]
请问目前支持从多个数据源抽取数据然后聚合成目标表中的一条记录？

**Comment by Breeze0806** [comment]
不行，这主要目前是迁移效率的问题，目前仅支持单源单表，但是你可以考虑先把t1和t2先行导入到你的目标库，然后在目标库做关联处理。
另外，本工具的定位是轻量级的etl，如果确实有需要这样的功能，你可以考虑一下flink。
